#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

build_folder=build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cp ../hoofdstukken/Voorpagina/*.* $build_folder
cd $build_folder

pandoc VoorpaginaLed.md -o ../../boeken/VoorpaginaLed.pdf
pandoc VoorpaginaSensor.md -o ../../boeken/VoorpaginaSensor.pdf
pandoc VoorpaginaActuatorenLaag.md -o ../../boeken/VoorpaginaActuatorenLaag.pdf
pandoc VoorpaginaActuatorenHoog.md -o ../../boeken/VoorpaginaActuatorenHoog.pdf
pandoc VoorpaginaMuziek.md -o ../../boeken/VoorpaginaMuziek.pdf
pandoc VoorpaginaNeoPixel.md -o ../../boeken/VoorpaginaNeoPixel.pdf
pandoc VoorpaginaTheremin.md -o ../../boeken/VoorpaginaTheremin.pdf


