#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

build_folder=build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cp ../hoofdstukken/Voorwoord/*.* $build_folder                                    ; mv $build_folder/README.md $build_folder/README_00.md
cp ../hoofdstukken/5_dc_motor_met_transistor/*.* $build_folder                    ; mv $build_folder/README.md $build_folder/README_01.md
cp ../hoofdstukken/7_dc_motor_met_relais/*.* $build_folder                        ; mv $build_folder/README.md $build_folder/README_02.md
cp ../hoofdstukken/8_infrarood_sensor_obstakel_ontwijkend_object/*.* $build_folder; mv $build_folder/README.md $build_folder/README_03.md

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md

# Thinner margin
pandoc README.md -o boek.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

cp boek.pdf ../../boeken/Boek_actuatoren_hoog_zonder_voorpagina.pdf

cd ../../boeken

pdfunite VoorpaginaActuatorenHoog.pdf Boek_actuatoren_hoog_zonder_voorpagina.pdf Boek_actuatoren_hoog.pdf

# Make booklet
bookletimposer -a Boek_actuatoren_hoog.pdf -o Boekje_actuatoren_hoog.pdf

# Cleanup
rm Boek_actuatoren_hoog_zonder_voorpagina.pdf
