# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: Build Booklets

jobs:
  build_booklets:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pdftk, for splitting PDFs
        run: sudo apt-get install pdftk

      - name: Create booklets
        run: |
          cd scripts
          ./maak_boek_voorpaginas
          ./maak_boek_1_led_en_knop
          ./maak_boek_2_leds_en_sensoren
          ./maak_boek_3_actuatoren_laag
          ./maak_boek_4_actuatoren_hoog
          ./maak_boek_5_muziek
          ./maak_boek_6_theremin
          ./maak_boek_neopixel

      - name: Zip booklets
        run: zip boeken.zip boeken/*.pdf

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: boeken_zip
          path: boeken.zip

